export const WORK_EXPERIENCE = [
    'Student',
    'Entry-level',
    'Mid-level',
    'Senior-level',
    'Staff-level',
    'Executive'
];

export const EDUCATION_LEVEL = [
    'High School',
    'Associate',
    'Bachelor',
    'Master',
    'Doctorate'
];

export const COURSE_LEVELS = [
    'Beginner',
    'Intermediate',
    'Advanced'
];

export const COURSE_STATUSES = [
    'In-Progress',
    'Completed'
];

export const CATEGORIES = {
    'Computer Science': [
        'Data Structures & Algorithms',
        'Programming Languages',
        'Computer Networking',
        'Operating Systems',
        'Databases',
        'Frontend Development',
        'Backend Development',
        'Mobile Development',
        'Game Development',
        'Software Engineering',
        'Data Science',
        'Artificial Intelligence',
        'Cybersecurity',
    ],
    'Arts & Crafts': [
        'Drawing',
        'Painting',
        'Sculpting',
        'Photography',
        'Music',
        'Dance',
        'Theater',
        'Writing',
        'Fashion',
        'Culinary',
    ],
    'Business': [
        'Entrepreneurship',
        'Marketing',
        'Finance',
        'Accounting',
        'Economics',
        'Management',
        'Leadership',
        'Human Resources',
        'Project Management',
        'Business Analysis',
        'Sales',
        'Customer Service',
        'Business Communication',
    ],
    'Culinary': [
        'Baking',
        'Cooking',
        'Mixology',
        'Food Photography',
        'Food Styling',
        'Food Writing',
    ],
    'Design': [
        'Graphic Design',
        'Web Design',
        'UI/UX Design',
        'Product Design',
        'Interior Design',
        'Fashion Design',
        'Industrial Design',
        'Game Design',
        'Animation',
        'Illustration',
    ],
    'Education': [
        'Early Childhood Education',
        'Elementary Education',
        'Secondary Education',
        'Special Education',
        'Adult Education',
        'Higher Education',
        'Curriculum Development',
        'Instructional Design',
        'Educational Technology',
        'Educational Leadership',
        'Educational Administration',
    ],
    'Fashion': [
        'Fashion Design',
        'Fashion Styling',
        'Fashion Photography',
        'Fashion Writing',
        'Fashion Business',
        'Fashion Marketing',
    ],
    'Finance': [
        'Personal Finance',
        'Investing',
        'Retirement Planning',
        'Tax Preparation',
        'Estate Planning',
        'Financial Analysis',
        'Financial Planning',
        'Financial Management',
        'Financial Reporting',
        'Financial Modeling',
        'Financial Accounting',
        'Managerial Accounting',
    ],
    'Health & Fitness' : [
        'Nutrition',
        'Exercise',
        'Yoga',
        'Meditation',
        'Strength Training',
        'Cardio',
        'Pilates',
        'Barre',
        'Dance',
        'Physical Therapy',
        'Occupational Therapy',
        'Speech Therapy',
        'Massage Therapy',
        'Acupuncture',
        'Chiropractic',
        'Naturopathic Medicine',
        'Homeopathy',
        'Ayurveda',
        'Traditional Chinese Medicine',
        'Herbal Medicine',
        'Holistic Medicine',
        'Integrative Medicine',
        'Functional Medicine',
        'Preventative Medicine',
        'Regenerative Medicine',
        'Aesthetic Medicine',
        'Plastic Surgery',
        'Dermatology',
        'Ophthalmology',
        'Optometry',
        'Audiology',
        'Dentistry'
    ],
    'Language': [
        'Spanish',
        'French',
        'German',
        'Chinese',
        'Japanese',
        'Korean',
        'Italian',
        'Portuguese',
        'Russian',
        'Arabic',
    ],
    'Music' : [
        'Piano',
        'Guitar',
        'Violin',
        'Cello',
        'Bass',
        'Drums',
        'Saxophone',
        'Trumpet',
        'Trombone',
        'Clarinet',
        'Flute',
        'Oboe',
        'Bassoon',
        'French Horn',
        'Harp',
        'Voice',
        'Music Theory',
        'Music Composition',
        'Music Production',
        'Music Engineering',
        'Music Business',
        'Music Education',
    ],
    'Photography': [
        'Landscape Photography',
        'Portrait Photography',
        'Event Photography',
        'Wedding Photography',
        'Fashion Photography',
        'Food Photography',
        'Product Photography',
        'Real Estate Photography',
        'Architectural Photography',
        'Travel Photography',
        'Street Photography',
        'Documentary Photography',
        'Photojournalism',
        'Wildlife Photography',
        'Nature Photography',
        'Astrophotography',
        'Macro Photography',
        'Black & White Photography',
        'Color Photography',
        'Digital Photography',
        'Film Photography',
        'Analog Photography',
        'Darkroom Photography',
        'Lightroom Photography',
        'Photoshop Photography',
        'Photography Business',
        'Photography Marketing',
        'Photography Sales',
        'Photography Writing',
    ],
    'Technology': [
        'Computer Science',
        'Information Technology',
        'Software Development',
        'Web Development',
        'Mobile Development',
        'Game Development',
        'Data Science',
        'Artificial Intelligence',
        'Machine Learning',
        'Cybersecurity',
        'Network Security',
        'Cloud Computing',
        'DevOps',
        'Systems Administration',
        'Database Administration',
        'IT Management',
        'IT Leadership',
        'IT Project Management',
        'IT Business Analysis',
        'IT Sales',
        'IT Marketing',
        'IT Writing',
    ],
    'Writing': [
        'Creative Writing',
        'Fiction Writing',
        'Nonfiction Writing',
        'Poetry Writing',
        'Screenwriting',
        'Playwriting',
        'Journalism',
        'Blogging',
        'Copywriting',
        'Technical Writing',
        'Grant Writing',
        'Proposal Writing',
        'Speech Writing',
        'Ghostwriting',
        'Book Writing',
        'Editing',
        'Proofreading',
        'Publishing',
        'Self-Publishing',
        'Traditional Publishing',
        'Indie Publishing',
        'Literary Agent',
        'Literary Magazine',
        'Literary Journal',
        'Literary Press',
    ],
};

// list of major cities in the US sorted alphabetically
export const CITIES = [
    'Atlanta',
    'Austin',
    'Boston',
    'Chicago',
    'Dallas',
    'Denver',
    'Detroit',
    'Houston',
    'Los Angeles',
    'Miami',
    'Minneapolis',
    'New York',
    'Philadelphia',
    'Phoenix',
    'Portland',
    'San Francisco',
    'Seattle',
    'Washington'
];

